---
particleType: proton

source: #in
    type: scatter
    distance: 0.02
    divergence: 0.01
    energy: 40
    N: 10000

field: #in
    type: cocoon
    filename: fields/flash/lasslab_hdf5_plt_cnt_0300
    origin_z: 0.1050e-3
    B_scale: -10
    E_scale: 0
    origin: [0, 0.05, 0]
    axis: [0, 0, 1]
    theta: 0

detector:
    type: fluence
    distance: 1
    pixels: [200, 200]
    size: [0.0204, 0.0204]

integrator: #in
    type: RKDP
    time_step: 1.14e-15
    dt_min: 5e-16
    tol: 1e-3

interpolation:
    type: none
    source:
        type: scatter
        distance: 0.02
        divergence: 0.01
        energy: 40
        N: 100000
    iterations: 1
...
